### ISSUE TITLE
Import `fetch from 'fetch'` not working w/ 1.4.0

### ISSUE THREAD

**Issue by nickschot** [stefanpenner/ember-fetch#26]
Doing `import fetch from 'fetch'` throws a `ember.debug.js:18015 Error: Could not find module 'fetch'` on 1.4.0. Works fine on 1.3.0

- Ember-Cli 2.12.1 w/ latest dependencies
- Node 7.4.0

**Comment by ef4** [comment]
Can you check if your app has ember-network in its dependencies? `npm ls | grep ember-network`

If so I think #27 solves this.

**Comment by nickschot** [comment]
Not explicitly, it seems that ember-simple-auth included ember-network as a dependency.

From #21 I chose ember-fetch instead of ember-network for my own needs.

Thanks for the quick fix guys!

**Comment by ef4** [comment]
We should PR ember-simple-auth to switch to this one.

**Comment by nickschot** [comment]
@ef4 and maybe fastboot too? Just stumbled upon the guide: https://ember-fastboot.com/quickstart

**Comment by BlueRaja** [comment]
We are seeing this issue in a large project, running the latest version (3.2.8), with no dependencies running `ember-network`.  Reverting to 1.3.0 does fix the issue.  No idea how to even debug this.

**Comment by ef4** [comment]
@BlueRaja this bug was fixed in ember-fetch version 1.4.2. If you are on that version or newer, please open a separate issue.
